$ErrorActionPreference  = "SilentlyContinue"
$ProgressPreference     = "SilentlyContinue"
$WarningPreference      = "SilentlyContinue"
$VerbosePreference      = "SilentlyContinue"
$ConfirmPreference      = "None"

# ============================================================
# HELPER FUNCTIONS
# ============================================================
function RegSet($path, $name, $value, $type = "DWord") {
    If (-not (Test-Path $path)) { New-Item -Path $path -Force | Out-Null }
    Set-ItemProperty -Path $path -Name $name -Value $value -Type $type -EA SilentlyContinue
}
function SvcKill($name) {
    $s = Get-Service -Name $name -EA SilentlyContinue
    If ($s) {
        Stop-Service    $name -Force           -EA SilentlyContinue
        Set-Service     $name -StartupType Disabled -EA SilentlyContinue
        sc.exe config   $name start= disabled  2>$null | Out-Null
    }
}
function SvcEnable($name, $startType = "Automatic") {
    $s = Get-Service -Name $name -EA SilentlyContinue
    If ($s) {
        Set-Service  $name -StartupType $startType -EA SilentlyContinue
        sc.exe config $name start= auto 2>$null | Out-Null
        Start-Service $name -EA SilentlyContinue
    }
}

# ============================================================
# [A] POWER PLAN — "Final Premium V0.0.1 by Nelly Stephod"
#     .pow ถูก embed เป็น Base64 ในไฟล์นี้แล้ว — รันไฟล์เดียวจบ
# ============================================================
 
$planName = "Final Premium V0.0.1 by Nelly Stephod"
 
# ลบ plan เดิมที่ชื่อเดียวกัน (ถ้ามี)
powercfg -list 2>$null | Select-String $planName | ForEach-Object {
    $g = ($_ -split "\s+")[3]
    If ($g) { powercfg -delete $g 2>$null | Out-Null }
}
 
# Decode .pow จาก Base64 แล้ว import
$powB64  = "cmVnZgEAAAABAAAAr3sYI7y+3AEBAAAAAwAAAAAAAAABAAAAIAAAAABQAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEN5zF+sKvERr43cSj5XEFBDecxfrCrxEa+N3Eo+VxBQAAAAAER5zF+sKvERr43cSj5XEFBybXRtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgUJn0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhiaW4AAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiP///25rLACN2WsJur7cAQAAAAD/////EwAAAAAAAADgRwAA/////wIAAACwAgAAmAAAAP////9IAAAAAAAAABgAAABoAAAAAAAAACQAAAAwMTAwMTAxMS0wMTAwLTExMTEtMDEwMS0wMDExODg4ODg4ODQAAAAAAP///3NrAACYAAAAmAAAAFsAAADoAAAAAQAEjNAAAADcAAAAAAAAABQAAAACALwACAAAAAAQGAA/AA8AAQIAAAAAAAUgAAAAIAIAAAAbGAAAAAAQAQIAAAAAAAUgAAAAIAIAAAAQGAAZAAIAAQIAAAAAAAUgAAAAIQIAAAAaGAAAAACAAQIAAAAAAAUgAAAAIQIAAAAaGAAAAACAAQIAAAAAAAUgAAAAIAIAAAAQFAA/AA8AAQEAAAAAAAUSAAAAABoUAAAAABABAQAAAAAABRIAAAAAGhQAAAAAgAEBAAAAAAADAAAAAAEBAAAAAAAFEgAAAAEBAAAAAAAFEgAAANj///92awsAaAAAAMABAAACAAAAAQAAAERlc2NyaXB0aW9uAAAAAACI////VQBsAHQAcgBhACAAbABvAHcAIABsAGEAdABlAG4AYwB5ACAAKwAgAG0AYQB4ACAAcABlAHIAZgBvAHIAbQBhAG4AYwBlACAAZgBpAHYAZQBtACAAbwBwAHQAaQBtAGkAegBlAHIAAAA1ADAAAAAAAAAAAADY////dmsMAEwAAABgAgAAAgAAAAEAAABGcmllbmRseU5hbWUAAAAAsP///0YAaQBuAGEAbAAgAFAAcgBlAG0AaQB1AG0AIABWADAALgAwAC4AMQAgAGIAeQAgAE4AZQBsAGwAeQAgAFMAdABlAHAAaABvAGQAAADw////mAEAADgCAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgAAAACQAAAAAAAADwCQAA/////wAAAAD/////mAAAAP////9IAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAwMDEyZWU0Ny05MDQxLTRiNWQtOWI3Ny01MzVmYmE4YjE0NDIAAAAA8P///2xmAQCoCwAANGM3OYj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAIAQAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMGIyZDY5ZDctYTJhMS00NDljLTk2ODAtZjkxYzcwNTIxYzYwAAAAAPD////ABAAA6AQAADBiMmTY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD////QAwAA+AMAAAAAAACI////bmsgAERG0EenutwBAAAAAMACAAAAAAAAAAAAAP//////////AgAAAMADAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADY3MzhlMmM0LWU4YTUtNGE0Mi1iMTZhLWUwNDBlNzY5NzU2ZQAAAADw////sAUAANgFAAAwYjJk+P///1AHAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAqAQAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAODBlM2M2MGUtYmI5NC00YWQ4LWJiZTAtMGQzMTk1ZWZjNjYzAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQA1C0FDU2V0dGluZ0luZGV4FyjY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAyAYAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZDNkNTVlZmQtYzFmZi00MjRlLTlkYzMtNDQxYmU3ODMzMDEwAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///3gGAACgBgAAAAAAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAuAcAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZDYzOTUxOGEtZTU2ZC00MzQ1LThhZjItYjlmMzJmYjI2MTA5AAAAANj///92aw4ABAAAgAAAAAAEAAAAAQA1C0FDU2V0dGluZ0luZGV4Fyjw////yAoAAPAKAABkYWI2+P///5gNAADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///4gFAACQBwAAAAAAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAkAgAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZGFiNjAzNjctNTNmZS00ZmJjLTgyNWUtNTIxZDA2OWQyNDU2AAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///0AIAABoCAAAAAAAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAaAkAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZGJjOWUyMzgtNmRlOS00OWUzLTkyY2QtOGMyYjQ5NDZiNDcyAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///xgJAABACQAAAAAAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8BAAAAuAQAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZmM3MzcyYjYtYWIyZC00M2VlLTg3OTctMTVlOTg0MWYyY2NhAAAAAKD///9sZgkASAMAADBiMmQwBAAANjczOBAFAAA4MGUzAAYAAGQzZDXYBgAAZDYzOcgHAABkYWI2oAgAAGRiYzl4CQAAZmM3M1AKAABmYzk1AAAAAAAAAAAAAAAAAAAAAIj///9uayAAREbQR6e63AEAAAAAwAIAAAAAAAAAAAAA//////////8CAAAAeAcAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZmM5NWFmNGQtNDBlNy00YjZkLTgzNWEtNTZkMTMxZGJjODBlAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAAiP///25rIABERtBHp7rcAQAAAAAgAAAAAQAAAAAAAAA4AwAA/////wAAAAD/////mAAAAP////9IAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAwMmY4MTViNS1hNWNmLTRjODQtYmYyMC02NDlkMWY3NWQzZDgAAAAA8P///2xmAQAgDQAAMzA5ZPj///84DgAAiP///25rIABERtBHp7rcAQAAAAAYCwAAAAAAAAAAAAD//////////wIAAABwDAAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA0Yzc5M2U3ZC1hMjY0LTQyZTEtODdkMy03YTBkMmY1MjNjY2QAAAAA2P///3ZrDgAEAACAAQAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAEAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////IAwAAEgMAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgAAAAAQAAAAAAAACQCwAA/////wAAAAD/////mAAAAP////9IAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAwZDdkYmFlMi00Mjk0LTQwMmEtYmE4ZS0yNjc3N2U4NDg4Y2QAAAAA8P///2xmAQAYDwAAMTJiYvD///+QDwAAuA8AADBkN2T4////EBEAAIj///9uayAAREbQR6e63AEAAAAAgAwAAAAAAAAAAAAA//////////8BAAAAiAcAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMzA5ZGNlOWItYmVmNC00MTE5LTk5MjEtYTg1MWZiMTJmMGY0AAAAANj///92aw4ABAAAgAEAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAACAAAAAAAAAAAAAAAP//////////AQAAAKALAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADBlNzk2YmRiLTEwMGQtNDdkNi1hMmQ1LWY3ZDJkYWE1MWY1MQAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAAiP///25rIABERtBHp7rcAQAAAAAgAAAAAQAAAAAAAAD4DAAA/////wAAAAD/////mAAAAP////9IAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAxOWNiYjhmYS01Mjc5LTQ1MGUtOWZhYy04YTNkNWZlZGQwYzEAAAAA8P///2AZAACIGQAAMDg1M9j///92aw4ABAAAgAAAAAAEAAAAAQD+lUFDU2V0dGluZ0luZGV4VWP4////SCgAAIj///9uayAAREbQR6e63AEAAAAAYA4AAAAAAAAAAAAA//////////8CAAAACA0AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMTJiYmViZTYtNThkNi00NjM2LTk1YmItMzIxN2VmODY3YzFhAAAAANj///92aw4ABAAAgAAAAAADAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAAAwAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///8gRAADwEQAAMjVkZvD///+4EgAA4BIAAAAAAABoYmluABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIj///9uayAAREbQR6e63AEAAAAAIAAAAAcAAAAAAAAASBQAAP////8AAAAA/////5gAAAD/////SAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAMjM4YzlmYTgtMGFhZC00MWVkLTgzZjQtOTdiZTI0MmM4ZjIwAAAAAIj///9uayAAREbQR6e63AEAAAAAIBAAAAAAAAAAAAAA//////////8BAAAAGA0AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMjVkZmExNDktNWRkMS00NzM2LWI1YWItZThhMzdiNWI4MTg3AAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAACAQAAAAAAAAAAAAAP//////////AgAAAOAPAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADI5ZjZjMWRiLTg2ZGEtNDhjNS05ZmRiLWYyYjY3YjFmNDRkYQAAAADw////gBMAAKgTAAAyNWRm+P///yAiAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAIBAAAAAAAAAAAAAA//////////8CAAAA8A8AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAN2JjNGEyZjktZDhmYy00NDY5LWIwN2ItMzNlYjc4NWFhY2EwAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQBlkEFDU2V0dGluZ0luZGV4JcrY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAIBAAAAAAAAAAAAAA//////////8CAAAAsBEAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAOTRhYzZkMjktNzNjZS00MWE2LTgwOWYtNjM2M2JhMjFiNDdlAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAAiP///25rIABERtBHp7rcAQAAAAAgEAAAAAAAAAAAAAD//////////wIAAACwFAAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAABhYmZjMjUxOS0zNjA4LTRjMmEtOTRlYS0xNzFiMGVkNTQ2YWIAAAAAwP///2xmBwCYEAAAMjVkZjgRAAAyOWY2GBIAADdiYzQIEwAAOTRhY9ATAABhYmZjwBQAAGJkM2KYFQAAZDRjMdj///92aw4ABAAAgAAAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////kBIAAIgUAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgEAAAAAAAAAAAAAD//////////wIAAACIFQAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAABiZDNiNzE4YS0wNjgwLTRkOWQtOGFiMi1lMWQyYjRhYzgwNmQAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////OBUAAGAVAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgEAAAAAAAAAAAAAD//////////wIAAABgFgAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAABkNGMxZDRjOC1kNWNjLTQzZDMtYjgzZS1mYzUxMjE1Y2IwNGQAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////EBYAADgWAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgAAAAAAAAAAAAAAD//////////wIAAAA4FwAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAAyNDVkODU0MS0zOTQzLTQ0MjItYjAyNS0xM2E3ODRmNjc5YjcAAAAA2P///3ZrDgAEAACAAQAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAIAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////6BYAABAXAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgAAAABAAAAAAAAAAoGgAA/////wAAAAD/////mAAAAP////9IAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAyYTczNzQ0MS0xOTMwLTQ0MDItOGQ3Ny1iMmJlYmJhMzA4YTMAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABAHpmQUNTZXR0aW5nSW5kZXj+ldj///92aw4ABAAAgAAAAAAEAAAAAQBj6kRDU2V0dGluZ0luZGV4GbXw////wBcAAOgXAAA0Zjk3iP///25rIABERtBHp7rcAQAAAABIFwAAAAAAAAAAAAD//////////wIAAADAGAAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAAwODUzYTY4MS0yN2M4LTQxMDAtYTJmZC04MjAxM2U5NzA2ODMAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD////oDgAAmBgAAAAAAACI////bmsgAERG0EenutwBAAAAAEgXAAAAAAAAAAAAAP//////////AgAAANgOAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADQ4ZTZiN2E2LTUwZjUtNDc4Mi1hNWQ0LTUzYmI4ZjA3ZTIyNgAAAADw////UBoAAHgaAAAwODUz+P///yA4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAASBcAAAAAAAAAAAAA//////////8CAAAASBkAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAANDk4YzA0NGEtMjAxYi00NjMxLWE1MjItNWM3NDRlZDRlNjc4AAAAANj///9sZgQAIBgAADA4NTPQGAAANDhlNrAZAAA0OThjoBoAAGQ0ZTnY////dmsOAAQAAIABAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAQAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAASBcAAAAAAAAAAAAA//////////8CAAAAaBsAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZDRlOThmMzEtNWZmZS00Y2UxLWJlMzEtMWIzOGIzODRjMDA5AAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///xgbAABAGwAAAAAAAIj///9uayAAREbQR6e63AEAAAAAIAAAAAMAAAAAAAAAMB4AAP////8AAAAA/////5gAAAD/////SAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAMmU2MDExMzAtNTM1MS00ZDlkLThlMDQtMjUyOTY2YmFkMDU0AAAAAIj///9uayAAREbQR6e63AEAAAAAeBsAAAAAAAAAAAAA//////////8CAAAAyBwAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMzE2NmJjNDEtN2U5OC00ZTAzLWIzNGUtZWMwZjVmMmIyMThlAAAAAPD///9oHQAAkB0AADMxNjbY////dmsOAAQAAID/////BAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACA/////wQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///94HAAAoBwAAAAAAACI////bmsgAERG0EenutwBAAAAAHgbAAAAAAAAAAAAAP//////////AgAAAGgcAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAAGMzNmYwZWI0LTI5ODgtNGE3MC04ZWVlLTA4ODRmYzJjMjQzMwAAAADw////WB4AAIAeAAAzMTY2+P///8A4AADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAeBsAAAAAAAAAAAAA//////////8CAAAAUB0AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZDUwMmY3ZWUtMWRjNy00ZWZkLWE1NWQtZjA0YjZmNWMwNTQ1AAAAANj///9sZgMA8BsAADMxNjbYHAAAYzM2ZrgdAABkNTAyAAAAAAAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAIAAAAAEAAAAAAAAAmB8AAP////8AAAAA/////5gAAAD/////SAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAANDg2NzJmMzgtN2E5YS00YmIyLThiZjgtM2Q4NWJlMTlkZTRlAAAAAIj///9uayAAREbQR6e63AEAAAAAqB4AAAAAAAAAAAAA//////////8CAAAAICAAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMmJmYzI0ZjktNWVhMi00ODAxLTgyMTMtM2RiYWUwMWFhMzlkAAAAAPD///9sZgEAIB8AADJiZmPY////dmsOAAQAAIABAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAQAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAAgAAAAAAAAAaGJpbgAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw////qB8AANAfAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAgAAAAAgAAAAAAAAAIIgAA/////wAAAAD/////mAAAAP////9IAAAAAAAAAAAAAAAAAAAAAAAAACQAAAA0Zjk3MWU4OS1lZWJkLTQ0NTUtYThkZS05ZTU5MDQwZTczNDcAAAAAiP///25rIABERtBHp7rcAQAAAAAwIAAAAAAAAAAAAAD//////////wIAAACAIQAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA5Njk5NmJjMC1hZDUwLTQ3ZWMtOTIzYi02ZjQxODc0ZGQ5ZWIAAAAA8P///2xmAQBQIwAAZWUxMtj///92aw4ABAAAgAEAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIABAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///zAhAABYIQAAAAAAAIj///9uayAAREbQR6e63AEAAAAAMCAAAAAAAAAAAAAA//////////8BAAAAwBEAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAOTlmZjEwZTctMjNiMS00YzA3LWE5ZDEtNWMzMjA2ZDc0MWI0AAAAAOj///9sZgIAqCAAADk2OTmQIQAAOTlmZtj///92aw4ABAAAgAEAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAACAAAAABAAAAAAAAACAhAAD/////AAAAAP////+YAAAA/////0gAAAAAAAAAAAAAAAAAAAAAAAAAJAAAADUwMWE0ZDEzLTQyYWYtNDQyOS05ZmQxLWE4MjE4YzI2OGUyMAAAAACI////bmsgAERG0EenutwBAAAAAGhHAAAAAAAAAAAAAP//////////AgAAAAhJAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADYzN2VhMDJmLWJiY2ItNDAxNS04ZTJjLWExYzdiOWMwYjU0Njc1MTbw////qEkAANBJAAA2Mzdl+P///3BKAACI////bmsgAERG0EenutwBAAAAAEgiAAAAAAAAAAAAAP//////////AgAAABAYAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAAGVlMTJmOTA2LWQyNzctNDA0Yi1iNmRhLWU1ZmExYTU3NmRmNQAAAACI////bmsgAERG0EenutwBAAAAACAAAAAZAAAAAAAAAPgyAAD/////AAAAAP////+YAAAA/////0gAAAAAAAAAAAAAAAAAAAAAAAAAJAAAADU0NTMzMjUxLTgyYmUtNDgyNC05NmMxLTQ3YjYwYjc0MGQwMAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAABglAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADA2Y2FkZjBlLTY0ZWQtNDQ4YS04OTI3LWNlN2JmOTBlYjM1ZAAAAADw////uCUAAOAlAAAwNmNh2P///3ZrDgAEAACAHgAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgB4AAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////yCQAAPAkAAAAAAAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wIAAAC4JAAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAAwNmNhZGYwZS02NGVkLTQ0OGEtODkyNy1jZTdiZjkwZWIzNWUAAAAA8P///6gmAADQJgAAMDZjYfj///8QKgAA2P///3ZrDgAEAACAPAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgDwAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAKAlAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADBjYzViNjQ3LWMxZGYtNDYzNy04OTFhLWRlYzM1YzMxODU4MwAAAADY////dmsOAAQAAIAUAAAABAAAAAEAGcJBQ1NldHRpbmdJbmRleC9X2P///3ZrDgAEAACAZAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgGQAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAMAnAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADEyYTBhYjQ0LWZlMjgtNGZhOS1iM2JkLTRiNjRmNDQ5NjBhNgAAAADY////dmsOAAQAAIAKAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACACgAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///9wJwAAmCcAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAALAoAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADEyYTBhYjQ0LWZlMjgtNGZhOS1iM2JkLTRiNjRmNDQ5NjBhNwAAAADY////dmsOAAQAAIAAAAAABAAAAAEAGcJEQ1NldHRpbmdJbmRleC9X8P///4grAACwKwAAMmRkZPj///9QLAAA2P///3ZrDgAEAACAFAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///+AJgAAiCgAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAIgpAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADJkZGQ1YTg0LTVhNzEtNDM3ZS05MTJhLWRiMGI4Yzc4ODczMgAAAADY////dmsOAAQAAIAHAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACABwAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///84KQAAYCkAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AQAAALAlAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADM2Njg3ZjllLWUzYTUtNGRiZi1iMWRjLTE1ZWIzODFjNjg2MwAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wEAAAAQDwAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAAzNjY4N2Y5ZS1lM2E1LTRkYmYtYjFkYy0xNWViMzgxYzY4NjQAAAAA2P///3ZrDgAEAACAAwAAAAQAAAABABnCQUNTZXR0aW5nSW5kZXgvV9j///92aw4ABAAAgAMAAAAEAAAAAQDkFERDU2V0dGluZ0luZGV41+Lw////sCoAANgqAAA0NWJjiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wIAAABwKAAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAAzYjA0ZDRmZC0xY2M3LTRmMjMtYWIxYy1kMTMzNzgxOWM0YmIAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AQAAAIAoAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADQwZmJlZmM3LTJlOWQtNGQyNS1hMTg1LTBjZmQ4NTc0YmFjNgAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wIAAABALQAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA0NWJjYzA0NC1kODg1LTQzZTItODYwNS1lZTBlYzZlOTZiNTkAAAAA2P///3ZrDgAEAACAZAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgGQAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////8CwAABgtAAAAAAAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wIAAAAAKwAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA0NjVlMWY1MC1iNjEwLTQ3M2EtYWI1OC0wMGQxMDc3ZGM0MTgAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABABnCQUNTZXR0aW5nSW5kZXgvV9j///92aw4ABAAAgAAAAAAEAAAAAQDkFERDU2V0dGluZ0luZGV41+Lw////yC0AAPAtAAA0NWJj2P///3ZrDgAEAACAZAAAAAQAAAABAIqtQUNTZXR0aW5nSW5kZXjEl/j////QNQAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wIAAAAgLwAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA0YjkyZDc1OC01YTI0LTQ4NTEtYTQ3MC04MTVkNzhhZWUxMTkAAAAA2P///3ZrDgAEAACAZAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgCgAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////0C4AAPguAAAAAAAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wIAAAAgMAAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA0ZDJiMDE1Mi03ZDVjLTQ5OGItODhlMi0zNDM0NTM5MmEyYzUAAAAA2P///3ZrDgAEAACAiBMAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgA8AAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AAD4////qDAAAGhiaW4AMAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///6gvAADQLwAAAAAAAIj///9uayAAREbQR6e63AEAAAAAyCMAAAAAAAAAAAAA//////////8BAAAA+C8AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAANWQ3NmEyY2EtZThjMC00MDJmLWExMzMtMjE1ODQ5MmQ1OGFkAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAJgxAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADYxOWI3NTA1LTAwM2ItNGU4Mi1iN2E2LTRkZDI5YzMwMDk3MQAAAADY////dmsOAAQAAIBkAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAZAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///9IMQAAcDEAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAHAyAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADdiMjI0ODgzLWIzY2MtNGQ3OS04MTlmLTgzNzQxNTJjYmU3YwAAAADY////dmsOAAQAAIBkAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAPAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///8gMgAASDIAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAABguAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADdmMmY1Y2ZhLWYxMGMtNDgyMy1iNWUxLWU5M2FlODVmNDZiNQAAAAAo////bGYZAEAkAAAwNmNhKCUAADA2Y2EIJgAAMGNjNfgmAAAxMmEw0CcAADEyYTDAKAAAMmRkZJgpAAAzNjY4OCoAADM2NjgQKwAAM2IwNNgrAAA0MGZieCwAADQ1YmNQLQAANDY1ZVguAAA0YjkyMC8AADRkMmIwMAAANWQ3NtAwAAA2MTliqDEAADdiMjKAMgAAN2YyZtAzAAA4OTNkgDQAADg5M2RYNQAAOTNiOPg1AAA5NDNj0DYAADk0ZDOoNwAAYzdiZUg4AABkZmQxAAAAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAHA0AACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADg5M2RlZThlLTJiZWYtNDFlMC04OWM2LWI1NWQwOTI5OTY0YwAAAADY////dmsOAAQAAIBkAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///yguAABINAAAAAAAAIj///9uayAAREbQR6e63AEAAAAAyCMAAAAAAAAAAAAA//////////8CAAAASDUAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAODkzZGVlOGUtMmJlZi00MWUwLTg5YzYtYjU1ZDA5Mjk5NjRkAAAAANj///92aw4ABAAAgGQAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIBkAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P////g0AAAgNQAAAAAAAIj///9uayAAREbQR6e63AEAAAAAyCMAAAAAAAAAAAAA//////////8BAAAAUC4AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAOTNiOGI2ZGMtMDY5OC00ZDFjLTllZTQtMDY0NGU5MDBjODVkAAAAANj///92aw4ABAAAgAUAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAMA2AACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADk0M2M4Y2I2LTZmOTMtNDIyNy1hZDg3LWU5YTNmZWVjMDhkMQAAAADY////dmsOAAQAAIBVAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAVQAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///9wNgAAmDYAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AgAAAJg3AACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADk0ZDNhNjE1LWE4OTktNGFjNS1hZTJiLWU0ZDhmNjM0MzY3ZgAAAADY////dmsOAAQAAIABAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAQAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///9INwAAcDcAAAAAAACI////bmsgAERG0EenutwBAAAAAMgjAAAAAAAAAAAAAP//////////AQAAAFgZAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAAGM3YmUwNjc5LTI4MTctNGQ2OS05ZDAyLTUxOWE1MzdlZDBjNgAAAADY////dmsOAAQAAIACAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAAiP///25rIABERtBHp7rcAQAAAADIIwAAAAAAAAAAAAD//////////wEAAABgHQAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAABkZmQxMGQxNy1kNWViLTQ1ZGQtODc3YS05YTM0ZGRkMTVjODIAAAAA2P///3ZrDgAEAACAFAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAIAAAAAQAAAAAAAAAoDsAAP////8AAAAA/////5gAAAD/////SAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAANzUxNmI5NWYtZjc3Ni00NDY0LThjNTMtMDYxNjdmNDBjYzk5AAAAAIj///9uayAAREbQR6e63AEAAAAA6DgAAAAAAAAAAAAA//////////8CAAAAODoAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAMTdhYWEyOWItOGI0My00Yjk0LWFhZmUtMzVmNjRkYWFmMWVlAAAAAPD////YOgAAADsAADE3YWHY////dmsOAAQAAIB1AwAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAdQMAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD////oOQAAEDoAAAAAAACI////bmsgAKAN1BO6vtwBAAAAAOg4AAAAAAAAAAAAAP//////////AgAAANg5AACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADNjMGJjMDIxLWM4YTgtNGUwNy1hOTczLTZiMTRjYmNiMmI3ZQAAAADw////yDsAAPA7AAAxN2FhCAAAADNjMGLY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAhAMAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAA6DgAAAAAAAAAAAAA//////////8CAAAAwDoAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAANjg0YzNlNjktYTRmNy00MDE0LTg3NTQtZDQ1MTc5YTU2MTY3AAAAANj///9sZgQAYDkAADE3YWFIOgAAM2MwYig7AAA2ODRjGDwAAGFkZWTY////dmsOAAQAAIABAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAQAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAA6DgAAAAAAAAAAAAA//////////8CAAAA4DwAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAYWRlZDVlODItYjkwOS00NjE5LTk5NDktZjVkNzFkYWMwYmNiAAAAANj///92aw4ABAAAgGQAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AADY////dmsOAAQAAIBkAAAABAAAAAEAAABEQ1NldHRpbmdJbmRleAAA8P///5A8AAC4PAAAAAAAAIj///9uayAAREbQR6e63AEAAAAAIAAAAAYAAAAAAAAAmEEAAP////8AAAAA/////5gAAAD/////SAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAODYxOWI5MTYtZTAwNC00ZGQ4LTliNjYtZGFlODZmODA2Njk4AAAAAIj///9uayAAREbQR6e63AEAAAAA8DwAAAAAAAAAAAAA//////////8CAAAAQD4AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAANDY4ZmU3ZTUtMTE1OC00NmVjLTg4YmMtNWI5NmM5ZTQ0ZmQwAAAAAPD////gPgAACD8AADQ2OGbY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD////wPQAAGD4AAAAAAACI////bmsgAERG0EenutwBAAAAAPA8AAAAAAAAAAAAAP//////////AgAAAOA9AACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADQ5Y2IxMWE1LTU2ZTItNGFmYi05ZDM4LTNkZjQ3ODcyZTIxYgAAAADw////0D8AACBAAAA0NjhmCAAAADQ5Y2LY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAA8DwAAAAAAAAAAAAA//////////8CAAAAyD4AAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAANjBjMDdmZTEtMDU1Ni00NWNmLTk5MDMtZDU2ZTMyMjEwMjQyAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQDw0kFDU2V0dGluZ0luZGV4yrTY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAACAAAAAAAAABoYmluAEAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAAPA8AAAAAAAAAAAAAP//////////AgAAABBBAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADgyMDExNzA1LWZiOTUtNGQ0Ni04ZDM1LTQwNDJiMWQyMGRlZgAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD////AQAAA6EAAAAAAAACI////bmsgAERG0EenutwBAAAAAPA8AAAAAAAAAAAAAP//////////AgAAAABCAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADlmZTUyN2JlLTFiNzAtNDhkYS05MzBkLTdiY2YxN2I0NDk5MAAAAADA////bGYGAGg9AAA0NjhmUD4AADQ5Y2IwPwAANjBjMEhAAAA4MjAxIEEAADlmZTUQQgAAYzc2MwAAAAAAAAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///+oPwAA2EEAAAAAAACI////bmsgAERG0EenutwBAAAAAPA8AAAAAAAAAAAAAP//////////AgAAANhCAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAAGM3NjNlZTkyLTcxZTgtNDEyNy04NGViLWY2ZWQwNDNhM2UzZAAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///+IQgAAsEIAAAAAAACI////bmsgAERG0EenutwBAAAAACAAAAACAAAAAAAAAMBEAAD/////AAAAAP////+YAAAA/////0gAAAAAAAAAAAAAAAAAAAAAAAAAJAAAADk1OTZmYjI2LTk4NTAtNDFmZC1hYzNlLWY3YzNjMDBhZmQ0YgAAAACI////bmsgAERG0EenutwBAAAAAOhCAAAAAAAAAAAAAP//////////AgAAADhEAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADEwNzc4MzQ3LTEzNzAtNGVlMC04YmJkLTMzYmRhY2FhZGU0OQAAAADw////2EQAAABFAAAxMDc32P///3ZrDgAEAACAAQAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAEAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////6EMAABBEAAAAAAAAiP///25rIABERtBHp7rcAQAAAADoQgAAAAAAAAAAAAD//////////wIAAADYQwAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAAzNGM3Yjk5Zi05YTZkLTRiM2MtOGRjNy1iNjY5M2I3OGNlZjQAAAAA6P///2xmAgBgQwAAMTA3N0hEAAAzNGM32P///3ZrDgAEAACAAAAAAAMAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAAAAAADAAAAAQAAAERDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAACAAAAACAAAAAAAAAABHAAD/////AAAAAP////+YAAAA/////0gAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAGRlODMwOTIzLWE1NjItNDFhZi1hMDg2LWUzYTJjNmJhZDJkYQAAAACI////bmsgAERG0EenutwBAAAAAChFAAAAAAAAAAAAAP//////////AgAAAHhGAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAADEzZDA5ODg0LWY3NGUtNDc0YS1hODUyLWI2YmRlOGFkMDNhOAAAAADw////GEcAAEBHAAAxM2Qw2P///3ZrDgAEAACAZAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgGQAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AADw////KEYAAFBGAAAAAAAAiP///25rIABERtBHp7rcAQAAAAAoRQAAAAAAAAAAAAD//////////wIAAAAYRgAAmAAAAP////8AAAAAAAAAABwAAAAEAAAAAAAAACQAAAA1YzViYjM0OS1hZDI5LTRlZTItOWQwYi0yYjI1MjcwZjdhODEAAAAA6P///2xmAgCgRQAAMTNkMIhGAAA1YzVi2P///3ZrDgAEAACAAAAAAAQAAAABAAAAQUNTZXR0aW5nSW5kZXgAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAERDU2V0dGluZ0luZGV4AACI////bmsgAERG0EenutwBAAAAACAAAAACAAAAAAAAAJBJAAD/////AAAAAP////+YAAAA/////0gAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAGU3M2EwNDhkLWJmMjctNGYxMi05NzMxLThiMjA3NmU4ODkxZgAAAAAo////bGYTAMACAAAwMDEyGAsAADAyZjiADAAAMGQ3ZMANAAAwZTc5YA4AADE5Y2IgEAAAMjM4Y3AWAAAyNDVkSBcAADJhNzN4GwAAMmU2MKgeAAA0ODY3MCAAADRmOTdIIgAANTAxYcgjAAA1NDUz6DgAADc1MTbwPAAAODYxOehCAAA5NTk2KEUAAGRlODNoRwAAZTczYfhJAABmMTU1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAPD///+4SAAA4EgAAAAAAACI////bmsgAERG0EenutwBAAAAAGhHAAAAAAAAAAAAAP//////////AgAAADgjAACYAAAA/////wAAAAAAAAAAHAAAAAQAAAAAAAAAJAAAAGJjZGVkOTUxLTE4N2ItNGQwNS1iY2NjLWY3ZTUxOTYwYzI1OAAAAADo////bGYCAMAiAAA2MzdlGEkAAGJjZGXY////dmsOAAQAAIAAAAAABAAAAAEAAABBQ1NldHRpbmdJbmRleAAA2P///3ZrDgAEAACAAAAAAAQAAAABAAAARENTZXR0aW5nSW5kZXgAAIj///9uayAAREbQR6e63AEAAAAAIAAAAAAAAAAAAAAA//////////8BAAAASCMAAJgAAAD/////AAAAAAAAAAAcAAAABAAAAAAAAAAkAAAAZjE1NTc2ZTgtOThiNy00MTg2LWI5NDQtZWFmYTY2NDQwMmQ5AAAAANj///92aw4ABAAAgAAAAAAEAAAAAQAAAEFDU2V0dGluZ0luZGV4AABoBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
$powPath = "$env:TEMP\FinalPremium_NellyStephod.pow"
[IO.File]::WriteAllBytes($powPath, [Convert]::FromBase64String($powB64))
powercfg -import $powPath 2>$null | Out-Null
Remove-Item $powPath -EA SilentlyContinue
 
# หา GUID ที่ import มา แล้ว set active
$planGuid = ""
powercfg -list 2>$null | Select-String $planName | ForEach-Object {
    $m = [regex]::Match($_, "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
    If ($m.Success) { $planGuid = $m.Value }
}
If ($planGuid) { powercfg -setactive $planGuid 2>$null | Out-Null }
 
 

# ============================================================
# [B] KERNEL / CPU SCHEDULING
# ============================================================

RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl" "Win32PrioritySeparation" 38
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl" "IRQ8Priority"            1
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl" "IRQ16Priority"           2
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl" "IRQ9Priority"            1

# Power Throttling OFF
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling" "PowerThrottlingOff" 1

# Timer Resolution — 0.5ms
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" "GlobalTimerResolutionRequests" 1

# Spectre / Meltdown OFF (+5-15% CPU performance)
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" "MitigationOptions"      0 "QWord"
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" "MitigationAuditOptions" 0 "QWord"

# Context Switch Reduction
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" "DisableExceptionChainValidation" 1

# BCD
bcdedit /deletevalue useplatformclock   2>$null | Out-Null
bcdedit /set useplatformtick  yes       2>$null | Out-Null
bcdedit /set disabledynamictick yes     2>$null | Out-Null
bcdedit /set tscsyncpolicy    Enhanced  2>$null | Out-Null
bcdedit /set bootmenupolicy   Standard  2>$null | Out-Null
bcdedit /set nx               OptIn     2>$null | Out-Null

# Crash Control
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl" "AutoReboot"          0
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl" "CrashDumpEnabled"    0
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl" "LogEvent"            0
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl" "SendAlert"           0

# Kill Timeout
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control" "WaitToKillServiceTimeout" "250" "String"
RegSet "HKCU:\Control Panel\Desktop"            "WaitToKillAppTimeout"     "250" "String"
RegSet "HKCU:\Control Panel\Desktop"            "HungAppTimeout"           "250" "String"
RegSet "HKCU:\Control Panel\Desktop"            "AutoEndTasks"             "1"   "String"
RegSet "HKCU:\Control Panel\Desktop"            "ForegroundLockTimeout"    0
RegSet "HKCU:\Control Panel\Desktop"            "MenuShowDelay"            "0"   "String"

# ============================================================
# [C] NETWORK — ABSOLUTE MAXIMUM
# ============================================================

# --- C1: Nagle OFF + DelAck ทุก Interface ---
Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces" | ForEach-Object {
    Set-ItemProperty $_.PSPath "TcpAckFrequency" 1    -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "TCPNoDelay"      1    -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "TcpDelAckTicks"  0    -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "MTU"             1500 -Type DWord -EA SilentlyContinue
}

# --- C2: TCP Global Stack สุดขีด ---
$tcp = "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"
RegSet $tcp "DefaultTTL"                    64
RegSet $tcp "MaxUserPort"                   65534
RegSet $tcp "TcpTimedWaitDelay"             30
RegSet $tcp "TCPMaxDupAcks"                2
RegSet $tcp "SackOpts"                      1
RegSet $tcp "Tcp1323Opts"                   1
RegSet $tcp "EnablePMTUDiscovery"           1
RegSet $tcp "GlobalMaxTcpWindowSize"        16777216
RegSet $tcp "TcpWindowSize"                16777216
RegSet $tcp "MaxDupAcksForFastRetransmit"  2
RegSet $tcp "TCPMaxConnectRetransmissions"  2
RegSet $tcp "DisableTaskOffload"            0
RegSet $tcp "EnableDCA"                     1
RegSet $tcp "MaxFreeTcbs"                   65536
RegSet $tcp "MaxHashTableSize"              65536
RegSet $tcp "MaxConnections"                0xffffffff
RegSet $tcp "TcpMaxSackBlocks"              8
RegSet $tcp "EnableTCPChimney"              0
RegSet $tcp "EnableRSS"                     1
RegSet $tcp "EnableTCPA"                    1
RegSet $tcp "TCPInitialRTT"                 3
RegSet $tcp "KeepAliveTime"                 7200000
RegSet $tcp "KeepAliveInterval"             1000

# --- C3: UDP / AFD EXTREME ---
$afd = "HKLM:\SYSTEM\CurrentControlSet\Services\AFD\Parameters"
RegSet $afd "DefaultReceiveWindow"             1048576
RegSet $afd "DefaultSendWindow"               1048576
RegSet $afd "FastSendDatagramThreshold"       1500
RegSet $afd "MaxFastTransmit"                 32
RegSet $afd "NonBlockingSendSpecialBuffering"  1
RegSet $afd "DynamicSendBufferDisable"         0
RegSet $afd "MaxBufferredReceiveBytes"         33554432
RegSet $afd "MaxBufferredSendBytes"            33554432
RegSet $afd "DoNotForceSendAlways"             1
RegSet $afd "EnableDynamicBacklog"             1
RegSet $afd "MinimumDynamicBacklog"            20
RegSet $afd "MaximumDynamicBacklog"            65535
RegSet $afd "DynamicBacklogGrowthDelta"        10
RegSet $afd "IrpStackSize"                     14
RegSet $afd "PriorityBoost"                    1
RegSet $afd "TransmitIoLength"                 65536

# --- C4: WINSOCK ---
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters" "MaxSockAddrLength" 128
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\WinSock2\Parameters" "MinSockAddrLength" 16

# --- C5: netsh TCP ---
netsh int tcp set global autotuninglevel=normal        2>$null | Out-Null
netsh int tcp set global rsc=disabled                  2>$null | Out-Null
netsh int tcp set global timestamps=disabled           2>$null | Out-Null
netsh int tcp set global initialRto=2000               2>$null | Out-Null
netsh int tcp set global maxsynretransmissions=2       2>$null | Out-Null
netsh int tcp set global nonsackrttresiliency=disabled 2>$null | Out-Null
netsh int tcp set global ecncapability=disabled        2>$null | Out-Null
netsh int tcp set global fastopen=enabled              2>$null | Out-Null
netsh int tcp set global hystart=disabled              2>$null | Out-Null
netsh int tcp set global pacingprofile=off             2>$null | Out-Null

# --- C6: QoS ปลดล็อก ---
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Psched" "NonBestEffortLimit"  0
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Psched" "MaxOutstandingSends" 0
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\QOS"    "Tc Supported"        1

# MMCSS Network
RegSet "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" "NetworkThrottlingIndex" 0xffffffff
RegSet "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" "SystemResponsiveness"   0
RegSet "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" "NoLazyMode"             1

# --- C7: DNS สุดขีด ---
$adapters = Get-NetAdapter | Where-Object {
    $_.Status -eq "Up" -and
    $_.InterfaceDescription -notlike "*Virtual*" -and
    $_.InterfaceDescription -notlike "*Loopback*" -and
    $_.InterfaceDescription -notlike "*Bluetooth*"
}
ForEach ($a in $adapters) {
    Set-DnsClientServerAddress -InterfaceIndex $a.InterfaceIndex -ServerAddresses "1.1.1.1","1.0.0.1" -EA SilentlyContinue
}
ipconfig /flushdns 2>$null | Out-Null

$dns = "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters"
RegSet $dns "MaxCacheTtl"                86400
RegSet $dns "MaxNegativeCacheTtl"         0
RegSet $dns "NegativeSOACacheTime"        0
RegSet $dns "NetFailureCacheTime"         0
RegSet $dns "CacheHashTableBucketSize"    1
RegSet $dns "CacheHashTableSize"          384
RegSet $dns "MaxSOACacheEntryTtlLimit"    0
RegSet $dns "AdaptiveTimeoutInitialValue" 50

# --- C8: Network Adapter Advanced ---
$cpuCount = [int](Get-CimInstance Win32_Processor | Select-Object -First 1).NumberOfLogicalProcessors

ForEach ($a in $adapters) {
    $n = $a.Name

    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Receive Buffers"               -DisplayValue "4096"     -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Transmit Buffers"              -DisplayValue "4096"     -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Interrupt Moderation"          -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Interrupt Moderation Rate"     -DisplayValue "Off"      -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "TCP Checksum Offload (IPv4)"   -DisplayValue "Enabled"  -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "TCP Checksum Offload (IPv6)"   -DisplayValue "Enabled"  -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "UDP Checksum Offload (IPv4)"   -DisplayValue "Enabled"  -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "UDP Checksum Offload (IPv6)"   -DisplayValue "Enabled"  -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "IP Checksum Offload"           -DisplayValue "Tx Enabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Large Send Offload V2 (IPv4)"  -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Large Send Offload V2 (IPv6)"  -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Receive Side Scaling"          -DisplayValue "Enabled"  -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Flow Control"                  -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Energy Efficient Ethernet"     -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Green Ethernet"                -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Power Saving Mode"             -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Wake on Magic Packet"          -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Wake on Pattern Match"         -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Jumbo Packet"                  -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Jumbo Frame"                   -DisplayValue "Disabled" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Speed & Duplex"                -DisplayValue "1.0 Gbps Full Duplex" -EA SilentlyContinue
    Set-NetAdapterAdvancedProperty -Name $n -DisplayName "Packet Priority & VLAN"        -DisplayValue "Packet Priority & VLAN Disabled" -EA SilentlyContinue

    Set-NetAdapterRss -Name $n -NumberOfReceiveQueues ([Math]::Min($cpuCount,4)) -EA SilentlyContinue

    $pwr = Get-NetAdapterPowerManagement -Name $n -EA SilentlyContinue
    If ($pwr) {
        $pwr.ArpOffload        = "Disabled"
        $pwr.NSOffload         = "Disabled"
        $pwr.WakeOnMagicPacket = "Disabled"
        $pwr.WakeOnPattern     = "Disabled"
        $pwr | Set-NetAdapterPowerManagement -EA SilentlyContinue
    }
    Disable-NetAdapterPowerManagement -Name $n -EA SilentlyContinue
}

# --- C9: MSI Mode ทุก PCI Device ---
$pci = "HKLM:\SYSTEM\CurrentControlSet\Enum\PCI"
Get-ChildItem $pci -EA SilentlyContinue | ForEach-Object {
    Get-ChildItem $_.PSPath -EA SilentlyContinue | ForEach-Object {
        $msi = "$($_.PSPath)\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties"
        $aff = "$($_.PSPath)\Device Parameters\Interrupt Management\Affinity Policy"
        If (Test-Path $msi) {
            Set-ItemProperty $msi "MSISupported"   1 -Type DWord -EA SilentlyContinue
            Set-ItemProperty $msi "MessageNumber"  4 -Type DWord -EA SilentlyContinue
        }
        If (Test-Path $aff) {
            Set-ItemProperty $aff "DevicePolicy"          0 -Type DWord -EA SilentlyContinue
            Set-ItemProperty $aff "AssignmentSetOverride" 0 -Type DWord -EA SilentlyContinue
        }
    }
}

# --- C10: Firewall — FiveM ports ---
@(
    @{n="FiveM UDP IN  30120"; p="UDP"; d="in";  port=30120},
    @{n="FiveM UDP OUT 30120"; p="UDP"; d="out"; port=30120},
    @{n="FiveM TCP IN  30120"; p="TCP"; d="in";  port=30120},
    @{n="FiveM TCP OUT 30120"; p="TCP"; d="out"; port=30120},
    @{n="FiveM UDP IN  40120"; p="UDP"; d="in";  port=40120},
    @{n="FiveM UDP OUT 40120"; p="UDP"; d="out"; port=40120},
    @{n="FiveM UDP IN  30110"; p="UDP"; d="in";  port=30110},
    @{n="FiveM UDP OUT 30110"; p="UDP"; d="out"; port=30110}
) | ForEach-Object {
    netsh advfirewall firewall delete rule name=$_.n 2>$null | Out-Null
    netsh advfirewall firewall add rule name=$_.n protocol=$_.p dir=$_.d localport=$_.port action=allow 2>$null | Out-Null
}

# --- C11: Delivery Optimization OFF ---
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization" "DODownloadMode" 0
SvcKill "DoSvc"



# ============================================================
# [D] FiveM / CitizenFX DEEP TWEAKS
# ============================================================

RegSet "HKCU:\SOFTWARE\CitizenFX"         "net_maxPackets"       "128" "String"
RegSet "HKCU:\SOFTWARE\CitizenFX"         "net_showCondition"    "0"   "String"
RegSet "HKCU:\SOFTWARE\CitizenFX"         "game_enforcegameencryption" "0" "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netFrameTime"         "0"   "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "rateLimitBypass"      "1"   "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netTimeout"           "15000" "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netRateThreshold"     "0"   "String"

# IFEO — Process Priority
$ifeo = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options"
@("FiveM.exe","FiveM_b3095.exe","GTA5.exe","GTA5_Enhanced.exe",
  "CitizenFX_SubProcess.exe","FiveM_ChromeBrowser.exe","fivem_server.exe") | ForEach-Object {
    $p = "$ifeo\$_\PerfOptions"
    RegSet $p "CpuPriorityClass" 3
    RegSet $p "IoPriority"       3
    RegSet $p "PagePriority"     5
}

# MMCSS Tasks
$mm = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks"
@("Games","FiveM","GTA5") | ForEach-Object {
    $t = "$mm\$_"
    RegSet $t "Affinity"            0
    RegSet $t "Background Only"     "False" "String"
    RegSet $t "Clock Rate"          10000
    RegSet $t "GPU Priority"        8
    RegSet $t "Priority"            6
    RegSet $t "Scheduling Category" "High"  "String"
    RegSet $t "SFIO Priority"       "High"  "String"
}

# ============================================================
# [E] GPU — ABSOLUTE MAXIMUM
# ============================================================

$gpuDrv = "HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"
RegSet $gpuDrv "HwSchMode"    2
RegSet $gpuDrv "TdrDelay"     60
RegSet $gpuDrv "TdrDdiDelay"  60
RegSet $gpuDrv "TdrLevel"     0

# D3D Flip — ลด Present Latency
Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Control\Video" -Recurse -EA SilentlyContinue |
    Where-Object { $_.PSChildName -eq "0000" } | ForEach-Object {
    Set-ItemProperty $_.PSPath "D3DFlipMode"           2 -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "VRROptimizationEnable" 0 -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "PreferD3DFlip"         1 -EA SilentlyContinue
}

# NVIDIA driver tweaks
$nvDrv = "HKLM:\SYSTEM\CurrentControlSet\Services\nvlddmkm\Global\NVTweak"
RegSet $nvDrv "EnableMidBufferPreemption"    0
RegSet $nvDrv "EnableCEPreemption"           0
RegSet $nvDrv "EnableMidGfxPreemptionVGPU"  0
RegSet $nvDrv "RMGpsBandwidthBoostEnable"    1
RegSet $nvDrv "RMDeepL2"                     0
RegSet $nvDrv "RMFastGC"                     1

# ============================================================
# [F] RAM / MEMORY ABSOLUTE MAX
# ============================================================

$mem = "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management"
RegSet $mem "DisablePagingExecutive"          1
RegSet $mem "LargeSystemCache"                0
RegSet $mem "ClearPageFileAtShutdown"         0
RegSet $mem "HeapDeCommitFreeBlockThreshold"  0x00040000
RegSet $mem "HeapDeCommitTotalFreeThreshold"  0x00100000
RegSet $mem "NonPagedPoolSize"                0
RegSet $mem "PagedPoolSize"                   0
RegSet $mem "SessionPoolSize"                 48
RegSet $mem "SessionViewSize"                 192
RegSet $mem "PoolUsageMaximum"                96
RegSet $mem "PhysicalAddressExtension"        1

$pre = "$mem\PrefetchParameters"
RegSet $pre "EnablePrefetcher"     0
RegSet $pre "EnableSuperfetch"     0
RegSet $pre "EnableBootTrace"      0
RegSet $pre "EnableRobustCodegen"  0

$totalRAM = (Get-CimInstance Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum
RegSet $mem "IoPageLockLimit" ([Math]::Floor(($totalRAM / 1MB) * 0.75) * 1024)

RegSet $mem "LargePageDrivers" "*" "String"

# ============================================================
# [G] STORAGE / DISK
# ============================================================

fsutil behavior set disable8dot3      1 2>$null | Out-Null
fsutil behavior set disablelastaccess  1 2>$null | Out-Null
fsutil behavior set memoryusage        2 2>$null | Out-Null
fsutil behavior set mftzone            2 2>$null | Out-Null
fsutil behavior set encryptpagingfile  0 2>$null | Out-Null

Get-PhysicalDisk -EA SilentlyContinue | Set-PhysicalDisk -MediaType SSD -EA SilentlyContinue

# ============================================================
# [H] SERVICES KILL — ขั้นสุด
# ============================================================

@(
    "DiagTrack","dmwappushservice","WdiSystemHost","WdiServiceHost",
    "diagnosticshub.standardcollector.service","PcaSvc","wercplsupport","WerSvc",
    "XblAuthManager","XblGameSave","XboxGipSvc","XboxNetApiSvc",
    "WSearch",
    "SysMain",
    "Fax","PrintNotify","RemoteRegistry","TabletInputService",
    "SharedAccess","lmhosts","NvTelemetryContainer","DoSvc",
    "WpnService","CDPSvc","OneSyncSvc","UnistoreSvc","UserDataSvc",
    "SEMgrSvc","ScDeviceEnum","SCardSvr",
    "RetailDemo","MapsBroker","PhoneSvc","MessagingService",
    "wisvc","TrkWks","MSDTC","lfsvc","icssvc",
    "WbioSrvc",
    "BthAvctpSvc","bthserv",
    "AJRouter",
    "ALG",
    "Spooler",
    "browser"
) | ForEach-Object { SvcKill $_ }

RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" "AllowTelemetry"      0
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" "MaxTelemetryAllowed" 0

# ============================================================
# [FIX-NET] คืน Services ที่จำเป็น — ต้องรันหลัง SERVICES KILL
# เพื่อให้ dependency order ถูกต้อง ไอคอนเน็ตถึงจะกลับมา
# ============================================================

function SvcForceEnable($name, $startType = "Automatic") {
    sc.exe config $name start= auto 2>$null | Out-Null
    Set-Service  $name -StartupType $startType -EA SilentlyContinue
    Start-Service $name -EA SilentlyContinue
}

# Core network stack — ต้องเปิดก่อน
SvcForceEnable "BFE"        "Automatic"   # Base Filtering Engine (ต้องมีก่อน MpsSvc)
SvcForceEnable "nsi"        "Automatic"   # Network Store Interface (ต้องมีก่อน NlaSvc)
SvcForceEnable "Dhcp"       "Automatic"   # DHCP Client
SvcForceEnable "Dnscache"   "Automatic"   # DNS Client
SvcForceEnable "iphlpsvc"   "Automatic"   # IP Helper
SvcForceEnable "netprofm"   "Automatic"   # Network List Service
SvcForceEnable "NlaSvc"     "Automatic"   # Network Location Awareness
SvcForceEnable "Netman"     "Manual"      # Network Connections
SvcForceEnable "Wcmsvc"     "Automatic"   # Windows Connection Manager
SvcForceEnable "NcaSvc"     "Manual"      # Network Connectivity Assistant
SvcForceEnable "WlanSvc"    "Automatic"   # WLAN AutoConfig (WiFi icon)
SvcForceEnable "dot3svc"    "Manual"      # Wired AutoConfig (LAN icon)
SvcForceEnable "NetSetupSvc" "Manual"     # Network Setup Service

# Restart ตามลำดับ dependency
Start-Sleep -Milliseconds 500
Restart-Service nsi      -Force -EA SilentlyContinue
Start-Sleep -Milliseconds 300
Restart-Service netprofm -Force -EA SilentlyContinue
Start-Sleep -Milliseconds 300
Restart-Service NlaSvc   -Force -EA SilentlyContinue
Start-Sleep -Milliseconds 300
Restart-Service Netman   -Force -EA SilentlyContinue

# ============================================================
# [FIX-NVIDIA] คืน NVIDIA Services — ต้องรันหลัง SERVICES KILL
# (NvTelemetry ปิดได้ แต่ Display/Container/ShadowPlay ต้องเปิด)
# ============================================================

# Driver display หลัก — เปิดก่อน
SvcForceEnable "nvlddmkm"                        "Automatic"
Start-Sleep -Milliseconds 500
# NVIDIA Control Panel + GeForce Experience + ShadowPlay/Overlay
SvcForceEnable "NVDisplay.ContainerLocalSystem"  "Automatic"
SvcForceEnable "NvContainerLocalSystem"          "Automatic"
SvcForceEnable "NvContainerNetworkService"       "Automatic"

# Coolbits — เปิด OC / Advanced clock controls ใน NVCP
RegSet "HKLM:\SOFTWARE\NVIDIA Corporation\Global\NVTweak" "Coolbits" 24

# ปิดเฉพาะ Telemetry ตัวเดียว (ไม่ใช่ Container)
SvcKill "NvTelemetryContainer"

# ============================================================
# [I] WINDOWS DEFENDER — ลด impact + Exclude FiveM
# ============================================================

Set-MpPreference -DisableRealtimeMonitoring        $true -EA SilentlyContinue
Set-MpPreference -DisableBehaviorMonitoring        $true -EA SilentlyContinue
Set-MpPreference -DisableIOAVProtection            $true -EA SilentlyContinue
Set-MpPreference -DisableScriptScanning            $true -EA SilentlyContinue
Set-MpPreference -DisableArchiveScanning           $true -EA SilentlyContinue
Set-MpPreference -DisableIntrusionPreventionSystem $true -EA SilentlyContinue
Set-MpPreference -DisableEmailScanning             $true -EA SilentlyContinue
Set-MpPreference -DisableRemovableDriveScanning    $true -EA SilentlyContinue
Set-MpPreference -ScanAvgCPULoadFactor              5    -EA SilentlyContinue
Set-MpPreference -EnableLowCpuPriority             $true -EA SilentlyContinue
Set-MpPreference -MAPSReporting                    0     -EA SilentlyContinue
Set-MpPreference -SubmitSamplesConsent             2     -EA SilentlyContinue

@("$env:LOCALAPPDATA\FiveM","$env:ProgramFiles\FiveM","$env:ProgramFiles(x86)\FiveM") |
    ForEach-Object { Add-MpPreference -ExclusionPath $_ -EA SilentlyContinue }
@("FiveM.exe","GTA5.exe","GTA5_Enhanced.exe","CitizenFX_SubProcess.exe","fivem_server.exe") |
    ForEach-Object { Add-MpPreference -ExclusionProcess $_ -EA SilentlyContinue }

# ============================================================
# [J] INPUT / MOUSE — Ultra Low Latency
# ============================================================

RegSet "HKCU:\Control Panel\Mouse" "MouseSpeed"       "0"   "String"
RegSet "HKCU:\Control Panel\Mouse" "MouseThreshold1"  "0"   "String"
RegSet "HKCU:\Control Panel\Mouse" "MouseThreshold2"  "0"   "String"
RegSet "HKCU:\Control Panel\Mouse" "MouseHoverTime"   "0"   "String"
RegSet "HKCU:\Control Panel\Mouse" "DoubleClickSpeed" "500" "String"
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\mouclass\Parameters" "MouseDataQueueSize"  16
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\mouhid\Parameters"   "MouseDataQueueSize"  16
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\kbdclass\Parameters" "KeyboardDataQueueSize" 16
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\i8042prt\Parameters" "PollStatusIterations"  1

# Raw Input — ลด Input Lag เชิงลึก
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\mouclass\Parameters" "ConnectMultiplePorts" 0
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\kbdclass\Parameters" "ConnectMultiplePorts" 0

# HID — ลด polling latency
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\HidUsb\Parameters" "NoSelectiveSuspend" 1
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\HidUsb\Parameters" "SelectiveSuspendEnabled" 0

# ============================================================
# [K] VISUAL — OFF ทั้งหมด
# ============================================================

RegSet "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" "VisualFXSetting" 2
RegSet "HKCU:\Control Panel\Desktop"            "DragFullWindows"     "0" "String"
RegSet "HKCU:\Control Panel\Desktop\WindowMetrics" "MinAnimate"       "0" "String"
RegSet "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize" "EnableTransparency" 0

# Game DVR OFF
RegSet "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR" "AppCaptureEnabled"        0
RegSet "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR" "HistoricalCaptureEnabled" 0
RegSet "HKCU:\System\GameConfigStore" "GameDVR_Enabled"                        0
RegSet "HKCU:\System\GameConfigStore" "GameDVR_FSEBehaviorMode"                2
RegSet "HKCU:\System\GameConfigStore" "GameDVR_HonorUserFSEBehaviorMode"       1
RegSet "HKCU:\System\GameConfigStore" "GameDVR_DXGIHonorFSEWindowsCompatible" 1
RegSet "HKCU:\System\GameConfigStore" "GameDVR_EFSEFeatureFlags"               0
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR" "AllowgameDVR"      0

# Game Mode ON
RegSet "HKCU:\SOFTWARE\Microsoft\GameBar" "AutoGameModeEnabled"       1
RegSet "HKCU:\SOFTWARE\Microsoft\GameBar" "AllowAutoGameMode"         1
RegSet "HKCU:\SOFTWARE\Microsoft\GameBar" "UseNexusForGameBarEnabled" 0

# ============================================================
# [L] GROUP POLICY
# ============================================================

$pol = "HKLM:\SOFTWARE\Policies\Microsoft\Windows"
RegSet "$pol\WindowsUpdate\AU"        "NoAutoUpdate"                    0
RegSet "$pol\WindowsUpdate\AU"        "AUOptions"                       2
RegSet "$pol\WindowsUpdate\AU"        "ScheduledInstallDay"             0
RegSet "$pol\DeliveryOptimization"    "DODownloadMode"                  0
RegSet "$pol\DataCollection"          "AllowTelemetry"                  0
RegSet "$pol\DataCollection"          "MaxTelemetryAllowed"             0
RegSet "$pol\CurrentVersion\PushNotifications" "NoToastApplicationNotification" 1
RegSet "HKCU:\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications" "GlobalUserDisabled" 1

RegSet "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance" "MaintenanceDisabled" 1

powercfg /sleepstudy /output nul 2>$null | Out-Null
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Power" "EnergySaverBatteryThreshold" 0

# ============================================================
# [M] NTOSKRNL / SYSTEM EXTRAS
# ============================================================

RegSet "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting" "Disabled"        1
RegSet "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting" "DontSendAdditionalData" 1
RegSet "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting" "LoggingDisabled" 1

RegSet "HKLM:\SOFTWARE\Policies\Microsoft\SQMClient\Windows" "CEIPEnable" 0

RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\EventLog" "Start" 4

RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds" "AllowBuildPreview"          0
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds" "EnableConfigFlighting"      0

RegSet "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" "PowerdownAfterShutdown" "1" "String"
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power" "HiberbootEnabled"      0

# ============================================================
# [X] DEEP GAME TWEAKS — เน้นเกมเบื้องลึก ลด Input Lag / Net Lag
# ============================================================

# --- X1: HPET ปิด (ใช้ TSC แทน — ลด latency สุดขีด) ---
bcdedit /deletevalue useplatformclock 2>$null | Out-Null
bcdedit /set useplatformtick yes      2>$null | Out-Null
bcdedit /set disabledynamictick yes   2>$null | Out-Null

# ปิด HPET ผ่าน Device Manager (Registry)
Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Enum\ACPI" -EA SilentlyContinue |
    Where-Object { $_.PSChildName -like "PNP0103*" } |
    ForEach-Object {
        Get-ChildItem $_.PSPath -EA SilentlyContinue | ForEach-Object {
            Set-ItemProperty "$($_.PSPath)" "ConfigFlags" 1 -Type DWord -EA SilentlyContinue
        }
    }

# --- X2: NVIDIA Low Latency Mode สุดขีด ---
# Ultra Low Latency (Null rendering queue)
$nvProfile = "HKLM:\SYSTEM\CurrentControlSet\Services\nvlddmkm\Global\NVTweak"
RegSet $nvProfile "EnableMidBufferPreemption"       0   # ปิด preemption ระหว่าง buffer
RegSet $nvProfile "EnableCEPreemption"              0
RegSet $nvProfile "EnableGrGfxPreemption"           0   # ปิด Graphics preemption
RegSet $nvProfile "EnableMidGfxPreemptionVGPU"      0
RegSet $nvProfile "DisablePreemption"               1   # Force disable preemption
RegSet $nvProfile "RmGdiSharedMemoryPoolSize"       0
RegSet $nvProfile "NvContextPrimary"                1   # Primary context priority
RegSet $nvProfile "GpuPowerPolicy"                  1   # Maximize GPU power
RegSet $nvProfile "OverrideMaxPerf"                 1   # Override to max perf
RegSet $nvProfile "RMGpsBandwidthBoostEnable"       1
RegSet $nvProfile "RMDeepL2"                        0
RegSet $nvProfile "RMFastGC"                        1
RegSet $nvProfile "RmProfilingAdminOnly"            0

# NVIDIA DX Present Queue — ลด Frame queue
$nvDX = "HKLM:\SOFTWARE\NVIDIA Corporation\Global\NVTweak"
RegSet $nvDX "Coolbits"                    24
RegSet $nvDX "ForceMaxPerf"                1    # บังคับ Max Performance
RegSet $nvDX "FRL_FPS"                     0    # ปิด Frame Rate Limiter
RegSet $nvDX "PowerMizerEnable"            1
RegSet $nvDX "PowerMizerLevel"             1    # Level 1 = Max Performance
RegSet $nvDX "PowerMizerLevelAC"           1

# --- X3: Direct3D / DXGI ลด Input Lag ---
RegSet "HKCU:\SOFTWARE\Microsoft\Direct3D" "MaxRenderedFramesAhead" 1  # Frame buffer = 1 (ต่ำสุด)
RegSet "HKLM:\SOFTWARE\Microsoft\Direct3D" "MaxRenderedFramesAhead" 1

# OpenGL ลด latency
RegSet "HKCU:\SOFTWARE\NVIDIA Corporation\Global\Ansel" "Enable" 0  # ปิด Ansel (กิน overhead)

# --- X4: Shader Cache เปิด (ลด stutter ครั้งแรก) ---
RegSet "HKLM:\SOFTWARE\NVIDIA Corporation\Global\NVTweak" "ShaderDiskCacheMaxSize" 10737418240  # 10GB

# --- X5: CPU Affinity สำหรับ Game / NVIDIA IRQ ผ่าน Registry ---
# ตั้ง IRQ affinity ให้ NVIDIA ใช้ Core 0 (Physical CPU0) ลด latency
Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Enum\PCI" -EA SilentlyContinue |
    Where-Object { $_.PSChildName -like "VEN_10DE*" } |
    ForEach-Object {
        Get-ChildItem $_.PSPath -EA SilentlyContinue | ForEach-Object {
            $aff = "$($_.PSPath)\Device Parameters\Interrupt Management\Affinity Policy"
            If (-not (Test-Path $aff)) { New-Item -Path $aff -Force | Out-Null }
            Set-ItemProperty $aff "DevicePolicy"          4 -Type DWord -EA SilentlyContinue  # IrqPolicySpecifiedProcessors
            Set-ItemProperty $aff "AssignmentSetOverride" 1 -Type DWord -EA SilentlyContinue  # Core 0
        }
    }

# --- X6: MMCSS Boost เพิ่ม — ลด DPC Latency ---
$sysProf = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"
RegSet $sysProf "SystemResponsiveness"   0
RegSet $sysProf "NetworkThrottlingIndex" 0xffffffff
RegSet $sysProf "NoLazyMode"             1

# Tasks\Games สุดขีด
$gamesTask = "$sysProf\Tasks\Games"
RegSet $gamesTask "Affinity"            0
RegSet $gamesTask "Background Only"     "False" "String"
RegSet $gamesTask "Clock Rate"          10000    # 1ms timer
RegSet $gamesTask "GPU Priority"        8        # Max GPU priority
RegSet $gamesTask "Priority"            6        # MMCSS priority
RegSet $gamesTask "Scheduling Category" "High"   "String"
RegSet $gamesTask "SFIO Priority"       "High"   "String"

# --- X7: UDP Socket Low Latency (FiveM เน้น UDP) ---
# เพิ่ม UDP buffer size ต่อ socket
$afd2 = "HKLM:\SYSTEM\CurrentControlSet\Services\AFD\Parameters"
RegSet $afd2 "FastSendDatagramThreshold"      65536  # UDP ใหญ่ขึ้นก่อน buffer
RegSet $afd2 "TransmitWorker"                 1      # ใช้ worker thread ส่ง
RegSet $afd2 "AlwaysSendIfPossible"           1      # ส่งทันทีไม่รอ
RegSet $afd2 "BufferMultiplier"               4      # คูณ buffer × 4

# --- X8: Network Input Lag (Gaming latency) ---
# Disable Receive Side Coalescing — ลด RSC latency
netsh int tcp set global rsc=disabled 2>$null | Out-Null
# ลด Initial RTO ให้ต่ำสุด
netsh int tcp set global initialRto=1500 2>$null | Out-Null

# Nagle + DelAck ทุก Interface (ซ้ำให้แน่ใจ)
Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces" | ForEach-Object {
    Set-ItemProperty $_.PSPath "TcpAckFrequency" 1 -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "TCPNoDelay"      1 -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "TcpDelAckTicks"  0 -Type DWord -EA SilentlyContinue
}

# --- X9: Process IDLE Power Throttle ปิด (เฉพาะ Game) ---
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling" "PowerThrottlingOff" 1

# ปิด Idle Throttle สำหรับทุก process
@("FiveM.exe","GTA5.exe","GTA5_Enhanced.exe","CitizenFX_SubProcess.exe") | ForEach-Object {
    $throttlePath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\$_\PerfOptions"
    RegSet $throttlePath "CpuPriorityClass"       3  # High
    RegSet $throttlePath "IoPriority"             3  # High
    RegSet $throttlePath "PagePriority"           5
    RegSet $throttlePath "PowerThrottlingOff"     1  # ปิด throttle เฉพาะ process นี้
}

# --- X10: Large Page + Lock Memory สำหรับเกม ---
# เพิ่มสิทธิ์ Lock Pages in Memory (ต้องการ reboot)
$secPath = "HKLM:\SYSTEM\CurrentControlSet\Control\SecureBoot\State"
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" "LargePageMinimum" 0

# --- X11: CPU C-State ปิดผ่าน Registry (สำหรับ Intel) ---
# ลด Idle CPU latency — ไม่ให้ CPU เข้า deep sleep
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Processor" "Capabilities" 0x0007e066
# ปิด C1E, C3, C6 states
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\intelppm\Parameters" "MaxIdleImplementors" 0
# AMD equivalent
RegSet "HKLM:\SYSTEM\CurrentControlSet\Services\amdppm\Parameters"   "MaxIdleImplementors" 0

# --- X12: DirectX Shader Optimization ---
RegSet "HKLM:\SOFTWARE\Microsoft\DirectX" "LoadDebugRuntime"      0
RegSet "HKCU:\SOFTWARE\Microsoft\Direct3D" "DisableD3DDebug"      1
RegSet "HKCU:\SOFTWARE\Microsoft\Direct3D" "D3DXShaderDebugLevel" 0

# ============================================================
# [N] FIVEM DEEP TWEAKS — ลด Input Lag / Net Lag ระดับลึกสุด
#     เฉพาะตัวเกม FiveM — ปลอดภัย ไม่พังระบบ
# ============================================================

# --- N1: CitizenFX Network Stack สุดขีด ---
# net_maxPackets: จำนวน packet สูงสุดต่อ tick (default 32, max 128)
# เพิ่มให้ส่ง/รับ packet ได้มากขึ้นต่อ frame → ลด packet loss
RegSet "HKCU:\SOFTWARE\CitizenFX"         "net_maxPackets"             "128"   "String"
RegSet "HKCU:\SOFTWARE\CitizenFX"         "net_showCondition"          "0"     "String"
RegSet "HKCU:\SOFTWARE\CitizenFX"         "game_enforcegameencryption" "0"     "String"
RegSet "HKCU:\SOFTWARE\CitizenFX"         "cl_preferIPv6"              "0"     "String"

# --- N2: CitizenFX Network Timing ---
# netTimeout: timeout ก่อน disconnect (ms) — 15000 = 15วิ ป้องกัน kick จาก lag spike
# netFrameTime: "0" = ไม่จำกัด frame time สำหรับ network processing
# rateLimitBypass: "1" = bypass rate limiter ของ client
# netRateThreshold: "0" = ไม่มี threshold ที่จะลด rate
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netTimeout"          "15000" "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netFrameTime"        "0"     "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "rateLimitBypass"     "1"     "String"
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netRateThreshold"    "0"     "String"
# netReliableRetransmitTimeout: ลด timeout สำหรับ reliable channel retransmit
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "netReliableRetransmitTimeout" "800" "String"
# UseNewFrameScheduler: ใช้ scheduler ใหม่ที่ลด jitter
RegSet "HKCU:\SOFTWARE\CitizenFX\Network" "UseNewFrameScheduler"         "1"   "String"

# --- N3: GTA V / FiveM Process Priority ขั้นสุด ---
$ifeo = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options"
@(
    "FiveM.exe",
    "FiveM_b3095.exe",
    "GTA5.exe",
    "GTA5_Enhanced.exe",
    "CitizenFX_SubProcess.exe",
    "FiveM_ChromeBrowser.exe",
    "fivem_server.exe",
    "ROSLauncher.exe",
    "SocialClubHelper.exe"
) | ForEach-Object {
    $p = "$ifeo\$_\PerfOptions"
    RegSet $p "CpuPriorityClass"  3   # High CPU priority
    RegSet $p "IoPriority"        3   # High I/O priority
    RegSet $p "PagePriority"      5   # Max page priority
    RegSet $p "PowerThrottlingOff" 1  # ปิด throttle สำหรับ process นี้
}

# --- N4: MMCSS Tasks เพิ่ม FiveM/GTA profile ---
$mm = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks"
@("Games","FiveM","GTA5","GTA5_Enhanced") | ForEach-Object {
    $t = "$mm\$_"
    RegSet $t "Affinity"            0
    RegSet $t "Background Only"     "False" "String"
    RegSet $t "Clock Rate"          10000   # 1ms timer resolution
    RegSet $t "GPU Priority"        8       # Max GPU priority ใน MMCSS
    RegSet $t "Priority"            6       # MMCSS thread priority
    RegSet $t "Scheduling Category" "High"  "String"
    RegSet $t "SFIO Priority"       "High"  "String"
}

# --- N5: UDP Socket Tuning เฉพาะ FiveM (UDP-based) ---
# FiveM ใช้ UDP port 30120 เป็นหลัก
# เพิ่ม UDP send/receive buffer และลด latency
$afd3 = "HKLM:\SYSTEM\CurrentControlSet\Services\AFD\Parameters"
RegSet $afd3 "FastSendDatagramThreshold"      65536  # ส่ง UDP ขนาดใหญ่โดยไม่ buffer
RegSet $afd3 "AlwaysSendIfPossible"           1      # ส่งทันทีไม่รอ batch
RegSet $afd3 "TransmitWorker"                 1      # ใช้ dedicated worker thread
RegSet $afd3 "BufferMultiplier"               4      # คูณ socket buffer × 4
RegSet $afd3 "PriorityBoost"                  1      # boost priority หลังรับ packet

# --- N6: Nagle OFF + DelAck = 0 ทุก Interface (ยืนยันซ้ำ) ---
# Nagle Algorithm รวม packet เล็กๆ เพื่อประสิทธิภาพ แต่เพิ่ม latency
# ปิดเพื่อให้ FiveM ส่ง packet ทันทีทุกครั้ง
Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces" | ForEach-Object {
    Set-ItemProperty $_.PSPath "TcpAckFrequency" 1 -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "TCPNoDelay"      1 -Type DWord -EA SilentlyContinue
    Set-ItemProperty $_.PSPath "TcpDelAckTicks"  0 -Type DWord -EA SilentlyContinue
}

# --- N7: QoS DSCP Marking สำหรับ FiveM Traffic ---
# Tag packet ของ FiveM ด้วย DSCP EF (Expedited Forwarding = priority สูงสุด)
# Router/ISP ที่รองรับ QoS จะให้ packet นี้ผ่านก่อน
$qosPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\QOS"
If (-not (Test-Path $qosPath)) { New-Item -Path $qosPath -Force | Out-Null }

$fivemQos = "$qosPath\FiveM"
If (-not (Test-Path $fivemQos)) { New-Item -Path $fivemQos -Force | Out-Null }
Set-ItemProperty $fivemQos "Version"          "1.0"     -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "Application Name" "FiveM.exe" -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "DSCP Value"       46        -Type DWord  -EA SilentlyContinue  # EF = 46
Set-ItemProperty $fivemQos "Local Port"       "*"       -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "Local IP"         "*"       -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "Remote Port"      "30120"   -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "Remote IP"        "*"       -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "Protocol"         "UDP"     -Type String -EA SilentlyContinue
Set-ItemProperty $fivemQos "Throttle Rate"    "-1"      -Type String -EA SilentlyContinue

$gtaQos = "$qosPath\GTA5"
If (-not (Test-Path $gtaQos)) { New-Item -Path $gtaQos -Force | Out-Null }
Set-ItemProperty $gtaQos "Version"          "1.0"       -Type String -EA SilentlyContinue
Set-ItemProperty $gtaQos "Application Name" "GTA5.exe"  -Type String -EA SilentlyContinue
Set-ItemProperty $gtaQos "DSCP Value"       46          -Type DWord  -EA SilentlyContinue
Set-ItemProperty $gtaQos "Local Port"       "*"         -Type String -EA SilentlyContinue
Set-ItemProperty $gtaQos "Remote Port"      "*"         -Type String -EA SilentlyContinue
Set-ItemProperty $gtaQos "Throttle Rate"    "-1"        -Type String -EA SilentlyContinue

# --- N8: Firewall Rules FiveM — ครบทุก port ---
$fivemPorts = @(
    @{n="FiveM UDP IN  30120"; p="UDP"; d="in";  port="30120"},
    @{n="FiveM UDP OUT 30120"; p="UDP"; d="out"; port="30120"},
    @{n="FiveM TCP IN  30120"; p="TCP"; d="in";  port="30120"},
    @{n="FiveM TCP OUT 30120"; p="TCP"; d="out"; port="30120"},
    @{n="FiveM UDP IN  40120"; p="UDP"; d="in";  port="40120"},
    @{n="FiveM UDP OUT 40120"; p="UDP"; d="out"; port="40120"},
    @{n="FiveM UDP IN  30110"; p="UDP"; d="in";  port="30110"},
    @{n="FiveM UDP OUT 30110"; p="UDP"; d="out"; port="30110"},
    @{n="FiveM UDP IN  33000"; p="UDP"; d="in";  port="33000"},
    @{n="FiveM UDP OUT 33000"; p="UDP"; d="out"; port="33000"}
)
ForEach ($r in $fivemPorts) {
    netsh advfirewall firewall delete rule name=$r.n 2>$null | Out-Null
    netsh advfirewall firewall add rule name=$r.n protocol=$r.p dir=$r.d localport=$r.port action=allow 2>$null | Out-Null
}

# --- N9: Game DVR ปิดสนิท (ไม่ให้แย่ง GPU) ---
# แต่ NVIDIA ShadowPlay ยังทำงานได้ผ่าน NvContainer service (เปิดไว้แล้ว)
RegSet "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR" "AppCaptureEnabled"        0
RegSet "HKCU:\System\GameConfigStore"                            "GameDVR_Enabled"           0
RegSet "HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR"      "AllowgameDVR"              0

# --- N10: GPU Scheduling + Preemption ลด input lag ---
# Hardware-accelerated GPU scheduling (HAGS) — ลด latency CPU-GPU
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" "HwSchMode"   2
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" "TdrDelay"    60
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" "TdrLevel"    0

# MaxRenderedFramesAhead = 1 → ลด frame buffer ให้น้อยที่สุด → ลด input lag
RegSet "HKCU:\SOFTWARE\Microsoft\Direct3D" "MaxRenderedFramesAhead" 1
RegSet "HKLM:\SOFTWARE\Microsoft\Direct3D" "MaxRenderedFramesAhead" 1

# --- N11: Power Throttling OFF สำหรับทุก FiveM process ---
RegSet "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling" "PowerThrottlingOff" 1
@("FiveM.exe","GTA5.exe","GTA5_Enhanced.exe","CitizenFX_SubProcess.exe") | ForEach-Object {
    $tp = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\$_\PerfOptions"
    RegSet $tp "PowerThrottlingOff" 1
}

# ============================================================
# [O] APPLY FINAL — Flush DNS + Refresh Policy + Network Reset
# ============================================================

# Winsock / IP stack reset (ทำให้ network tweak มีผล)
netsh winsock reset        2>$null | Out-Null
netsh int ip reset         2>$null | Out-Null
netsh int tcp set global autotuninglevel=normal 2>$null | Out-Null

# Flush + re-register DNS
ipconfig /flushdns         2>$null | Out-Null
ipconfig /registerdns      2>$null | Out-Null

# Group Policy refresh
gpupdate /force /wait:0    2>$null | Out-Null
